# Generated by Django 3.0.7 on 2020-07-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='product_price',
        ),
    ]
