# Generated by Django 3.0.7 on 2020-06-25 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20200625_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='filtercategory',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductSubCategory'),
        ),
        migrations.AlterModelTable(
            name='productlistthumbnail',
            table='product_list_thumbnails',
        ),
    ]
