# Generated by Django 3.0.7 on 2020-06-25 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20200625_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistthumbnail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product'),
        ),
    ]
