# Generated by Django 3.0.7 on 2020-06-25 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20200625_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistthumbnail',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Color'),
        ),
        migrations.AlterField(
            model_name='productlistthumbnail',
            name='thumbnail_background_color',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
