# Generated by Django 3.0.7 on 2020-06-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_product_filter_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='color',
            name='product',
            field=models.ManyToManyField(related_name='colors', through='product.ProductImage', to='product.Product'),
        ),
        migrations.AddField(
            model_name='filterlist',
            name='product',
            field=models.ManyToManyField(related_name='filterlists', through='product.ProductFilter', to='product.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(related_name='products', through='product.ProductImage', to='product.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='filter_list',
            field=models.ManyToManyField(related_name='products', through='product.ProductFilter', to='product.FilterList'),
        ),
    ]
