# Generated by Django 3.0.7 on 2020-06-26 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20200626_1802'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommend_products', to='product.Product')),
                ('recommend_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.Product')),
            ],
            options={
                'db_table': 'recommend_products',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='recommend_product',
            field=models.ManyToManyField(through='product.RecommendProduct', to='product.Product'),
        ),
    ]
