# Generated by Django 3.0.7 on 2020-06-28 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20200626_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlistthumbnail',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_thumbnail', to='product.Product'),
        ),
    ]
