# Generated by Django 3.0.7 on 2020-06-29 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_auto_20200628_1531'),
        ('product', '0012_productprice'),
    ]

    operations = [
    ]
