# Generated by Django 3.0.7 on 2020-07-02 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productprice_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='user',
        ),
    ]
