# Generated by Django 3.0.7 on 2020-06-30 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200629_2133'),
        ('product', '0013_merge_20200629_2132'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='user_order',
        ),
        migrations.RemoveField(
            model_name='userorder',
            name='user',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product_quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
        ),
        migrations.AddField(
            model_name='userorder',
            name='order_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.OrderItem'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductPrice'),
        ),
        migrations.AlterField(
            model_name='userorder',
            name='order_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.OrderStatus'),
        ),
    ]
