# Generated by Django 3.0.7 on 2020-06-30 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_merge_20200629_2132'),
        ('cart', '0002_auto_20200630_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Color'),
        ),
    ]
