# Generated by Django 3.0.7 on 2020-07-02 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_account_product_price'),
        ('cart', '0004_auto_20200701_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_status',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order_time',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='user_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.OrderItem'),
        ),
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('final_price', models.DecimalField(decimal_places=2, max_digits=30, null=True)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('order_time', models.DateField(auto_now_add=True)),
                ('order_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.OrderStatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
            options={
                'db_table': 'user_orders',
            },
        ),
    ]
