# Generated by Django 3.0.7 on 2020-07-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_auto_20200702_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='final_price',
            field=models.IntegerField(null=True),
        ),
    ]
